name: s2s 
channels:
  - conda-forge
dependencies:
  - python=3.8
  # IDE
  - jupyter
  - jupyterlab
  - jupyter-server-proxy
  - tqdm
  # Input/Output
  - netcdf4
  - zarr
  # Numerics
  - climpred
  - esmtools
  - numpy
  - pandas
  - scipy
  - xarray
  - xskillscore
  # Performance
  - bottleneck
  - dask
  - numba
  # Visualization
  # Fixes a bug with dask dashboard.
  - bokeh<2.0.0
  - cartopy
  - matplotlib
  - nc-time-axis
  - proplot
  - seaborn
  - pip>=20.1
  - pip:
      - ncar_jobqueue
      - nb_black
